server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: res-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/note/**

        - id: ui-service
          uri: http://localhost:3000/
          predicates:
            - Path=/**